### PR TITLE
Support for remote scratch folders and reference data folders.

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by scanon** [comment]
@rsutormin We should probably merge this.  Do you remember the use case that motivated it?

**Comment by msneddon** [comment]
@rsutormin This looks old- is this still something we should merge?

**Comment by scanon** [comment]
I think it was still useful.  @rsutormin ?

**Comment by msneddon** [comment]
And does it require any deployment configuration updates if we merge?

**Comment by rsutormin** [comment]
This PR is supposed to be wrong according to request from @MrCreosote asking for separate scratch area for each version of each module. In this PR separate scratch is implemented for each module and same folder is used for all versions of a module.

**Comment by rsutormin** [comment]
Actually I'm wrong :) Based on this line (https://github.com/kbase/service_wizard/pull/3/files#diff-1d4c9b37cc5e626d4912d8f4719bae2cR121) scratch folder is separate for each version of each module.

**Comment by MrCreosote** [comment]
> according to request from @MrCreosote asking for separate scratch area for each version of each module

Huh? not sure what this is talking about

**Comment by rsutormin** [comment]
I'm going to close it for now. I can make another attempt later.

**Pull request closed without merging**
