### PR TITLE
Do not expose system stacks in list_service_status (SCT-1294)

### PR DESCRIPTION
**Pull request by kkellerlbl**
With no arguments rancher.list_environment() lists all stacks, including system stacks like network and secrets.  These are exposed on the catalog web service page.  Users can't restart them or view logs but it still looks bad.  This argument should limit what list_environment returns to only user stacks.

### CODE REVIEW

**Comment by MrCreosote** [comment]
Are there no tests for this?

**Comment by kkellerlbl** [comment]
Testing specifically for system stacks?  I don't know.  I'm not even sure how it would do that.

**Review by briehl — APPROVED** [review]
Thanks for the pointer to their docs. This seems reasonable. But some way to test would be nice.

**Comment by MrCreosote** [comment]
Tests for the service wizard.

**Comment by kkellerlbl** [comment]
There's some sort of test code in there but it's definitely not running in Travis.

**Comment by MrCreosote** [comment]
I'm guessing you haven't run the tests. Someone should probably do that to make sure this doesn't break stuff. I'd be equally worried if the tests pass, though, which would mean this part of the code isn't tested.

**Comment by kkellerlbl** [comment]
I started setting up an environment to run tests but ran out of time.  If I can get set up relatively quickly then I'll try to run them but I'm not going to burn more than half a day on it.

The tests seem to require a Rancher instance, which complicates things.

**Comment by kkellerlbl** [comment]
''Tested'' live in CI, works fine, merging to build the real image.

**Pull request merged**
